name: app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  after_layout: any
  cached_network_image: ^2.3.3
  comment_box: ^0.0.15
  country_code_picker: ^2.0.1
  cupertino_icons: ^1.0.1
  dio: ^4.0.0
  # ff_navigation_bar: ^0.1.5
  flutter_dotenv: ^5.0.0
  flutter_easyloading: ^3.0.0
  flutter_html: ^2.1.0
  flutter_inappwebview: ^5.3.2
  flutter_mobx: ^2.0.0
  flutter_reorderable_list: ^1.0.0
  flutter_riverpod: ^0.12.1
  flutter_slidable: any
  flutter_speed_dial: ^3.0.5
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^0.22.0
  flutter_tags: ^0.4.9+1
  flutter_tts: ^3.0.0
  flutter_vector_icons: ^1.0.0
  font_awesome_flutter: ^9.1.0
  geolocator: ^6.1.6
  # getwidget: ^2.0.2
  global_configuration: any
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  http: ^0.13.3
  intl: ^0.17.0
  intl_phone_number_input: ^0.6.0
  json_annotation: ^3.1.1
  material_design_icons_flutter: ^4.0.5955
  nb_utils: ^4.3.0+3
  onesignal_flutter: ^3.0.0
  # otp_text_field: ^1.1.0
  package_info: ^2.0.2
  # path_provider: any
  photo_view: ^0.11.1
  queries: any
  rxdart: ^0.24.1
  settings_ui: any
  share: ^2.0.1
  shared_preferences: ^2.0.6
  skeleton_loader: ^1.0.2+3
  sliding_up_panel: ^2.0.0+1
  story_view: any
  table_calendar: ^3.0.0
  toast: ^0.1.5
  transparent_image: ^2.0.0
  url_launcher: ^6.0.5
  webview_flutter: any
  # webviewx: ^0.1.0
  # xml: any

module:
  androidX: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  faker: null
  hive_generator: null
  json_serializable: ^3.5.0
  mockito: null
  pedantic: null

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/cfg/
    #- resources/BibleDb.db
    - resources/esv.xml
    - resources/xml/
    - resources/raw/
    - assets/book.json
    - assets/images/matta_pic_1.jpg
    - assets/images/matta_pic_2.jpg
    - assets/images/matta_pic_3.jpg
    - assets/images/matta_pic_4.jpg
    - assets/images/matta_pic_5.jpg
    - assets/images/matta_pic_6.jpg
    - assets/images/matta_pic_7.jpg
    - assets/images/matta_pic_8.jpg
    - assets/images/matta_pic_9.jpg
    - assets/images/matta_pic_10.jpg
    - assets/images/pie.jpg
    - assets/images/drag_dots.png
    - assets/images/drag_lines.png
    - assets/svg/wizard1.svg
    - assets/svg/wizard2.svg
    - assets/svg/wizard3.svg
    - assets/images/csform_logo.png
    - assets/avatars/avatar_1.jpg
    - assets/avatars/avatar_2.jpg
    - assets/avatars/avatar_3.jpg
    - assets/avatars/avatar_4.jpg
    - assets/avatars/avatar_5.jpg
    - assets/avatars/avatar_6.jpg
    - assets/avatars/avatar_7.jpg
    - assets/avatars/avatar_8.jpg
    - assets/avatars/avatar_9.jpg
    - assets/avatars/avatar_10.jpg
    - assets/items.json
    - assets/pokemons.json
    - assets/images/
    - lang/en.json
    - lang/ar.json
    - assets/flags/
    - lang/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Thin.ttf
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-Italic.ttf
        - asset: assets/fonts/Lato-Bold.ttf
    - family: LaiSiangtho
      fonts:
        - asset: assets/fonts/LaiSiangtho.ttf
    - family: Mm3Web
      fonts:
        - asset: assets/fonts/Mm3Web.ttf
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/TitilliumWeb-Light.ttf
          weight: 300
        - asset: assets/fonts/TitilliumWeb-SemiBold.ttf
          weight: 600
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Book.ttf

        - asset: assets/fonts/CircularStd-Medium.ttf
          weight: 600

        - asset: assets/fonts/CircularStd-Black.ttf
          weight: 700

        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 900
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
